version: '3'

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./gateway:/usr/src/app
    networks:
      - app-network
    links:
      - heroes
      - movies

  heroes:
    build:
      context: ./heroes
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./heroes:/usr/src/app
    networks:
      - app-network
    links:
      - mongodb

  movies:
    build:
      context: ./movies
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./movies:/usr/src/app
    networks:
      - app-network
    links:
      - mongodb

  mongodb:
    image: mongo
    networks:
      - app-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    container_name: elasticsearch
    networks:
      - app-network
  elasticapm:
    image: docker.elastic.co/apm/apm-server:6.5.2
    container_name: elasticapm
    networks:
      - app-network
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.2
    container_name: kibana
    networks:
      - app-network
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

networks:
  app-network:
    driver: bridge
